# Generated by Django 4.1 on 2022-08-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_alter_order_options_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='friend',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='blue', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
